[project]
name = "hello-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain==1.2.2",
    "langchain-openai==1.1.7",
    "slack-bolt==1.27.0",
]
